In [20]:
import pandas as pd
import numpy as np
import psycopg2
import sqlalchemy as db
from sqlalchemy import create_engine
import yaml

with open('../config.yml', 'r') as f:
    config = yaml.safe_load(f)
    config_etl = config['ETL_PROCESS']

url_etl = (f"{config_etl['drivername']}://{config_etl['user']}:{config_etl['password']}@{config_etl['host']}:"
           f"{config_etl['port']}/{config_etl['dbname']}")

etl_conn = create_engine(url_etl)

In [21]:
p1 = pd.read_sql_query("""
    SELECT 
        f.mes, 
        COUNT(*) AS total_servicios
    FROM fact_servicio h
    JOIN dim_fechahora f ON h.fk_fecha_iniciado = f.fecha_hora_key
    WHERE h.fk_fecha_iniciado <> -1
    GROUP BY f.mes
    ORDER BY total_servicios DESC;
""", etl_conn)
p1

     mes  total_servicios
0    5.0             4725
1    7.0             4549
2    4.0             4480
3    8.0             4304
4    6.0             4184
5    3.0             3337
6    2.0             2479
7    1.0              296
8   12.0               25
9    9.0               21
10  11.0               17
11  10.0               12

In [22]:
p2 = pd.read_sql_query("""
    SELECT 
        f.dia_de_la_semana, 
        COUNT(*) AS total_solicitudes
    FROM fact_servicio h
    JOIN dim_fechahora f ON h.fk_fecha_iniciado = f.fecha_hora_key
    WHERE h.fk_fecha_iniciado <> -1
    GROUP BY f.dia_de_la_semana
    ORDER BY total_solicitudes DESC;
""", etl_conn)
p2

  dia_de_la_semana  total_solicitudes
0          Tuesday               5398
1           Friday               5281
2         Thursday               5160
3        Wednesday               4961
4           Monday               4308
5         Saturday               2481
6           Sunday                840

In [23]:
p3 = pd.read_sql_query("""
    SELECT 
        f.hora, 
        COUNT(*) AS servicios_recogidos
    FROM fact_servicio h
    JOIN dim_fechahora f ON h.fk_fecha_recogido = f.fecha_hora_key
    WHERE h.fk_fecha_recogido <> -1
    GROUP BY f.hora
    ORDER BY servicios_recogidos DESC;
""", etl_conn)
p3

    hora  servicios_recogidos
0   10.0                 3113
1   11.0                 3004
2    9.0                 2925
3   15.0                 2804
4    8.0                 2781
5   16.0                 2365
6   14.0                 2296
7   12.0                 2230
8   17.0                 1250
9   13.0                 1213
10   7.0                  500
11  18.0                  411
12  19.0                  366
13  20.0                  288
14  21.0                  210
15   0.0                  178
16   3.0                  169
17   1.0                  154
18  23.0                  152
19   2.0                  148
20   5.0                  131
21   6.0                  117
22   4.0                  104
23  22.0                   90

In [24]:
p4 = pd.read_sql_query("""
    SELECT 
        f.año, 
        f.mes, 
        c.nombre_cliente, 
        COUNT(*) AS total_servicios
    FROM fact_servicio h
    JOIN dim_cliente c ON h.fk_cliente = c.cliente_key
    JOIN dim_fechahora f ON h.fk_fecha_iniciado = f.fecha_hora_key
    WHERE h.fk_fecha_iniciado <> -1 AND h.fk_cliente <> -1
    GROUP BY f.año, f.mes, c.nombre_cliente
    ORDER BY f.año, f.mes, total_servicios DESC;
""", etl_conn)
p4

        año   mes                           nombre_cliente  total_servicios
0    2023.0   9.0                      CLINICA CALI -JOVEN               18
1    2023.0   9.0               CLINICA  DEPORTIVA DEL SUR                3
2    2023.0  10.0                      CLINICA CALI -JOVEN               12
3    2023.0  11.0                      CLINICA CALI -JOVEN               16
4    2023.0  11.0                           CRUZ AZUL-LIFE                1
..      ...   ...                                      ...              ...
102  2024.0   8.0  FUNDACION CLINICA INFANTIL LOS GRITONES               19
103  2024.0   8.0                           CRUZ AZUL-LIFE               16
104  2024.0   8.0          CLINICA SAN RAFAEL DE OCCIDENTE                3
105  2024.0   8.0                                Cliente 1                2
106  2024.0   8.0                          MEDICOS Y SALUD                1

[107 rows x 4 columns]

In [25]:
p5 = pd.read_sql_query("""
    SELECT 
        m.nombre_completo, 
        COUNT(*) AS servicios_entregados
    FROM fact_servicio h
    JOIN dim_mensajero m ON h.fk_mensajero = m.mensajero_key
    WHERE h.fk_mensajero <> -1 AND h.fk_fecha_entregado <> -1
    GROUP BY m.nombre_completo
    ORDER BY servicios_entregados DESC;
""", etl_conn)
p5

      nombre_completo  servicios_entregados
0         JHONTROCHEZ                  2429
1     Sebastian Acuña                  1505
2         Juan Solano                  1465
3     ANDRESGUTIERREZ                  1425
4          Jan Sastre                  1309
5      Hector Aquiles                  1304
6         LUISCARDONA                  1304
7            JPEDROZA                  1231
8       Jairon Montes                  1214
9           JHONMUÑOZ                  1190
10  Carlos Valderrama                  1080
11  ALEXANDERMOSQUERA                  1030
12        Luis Castro                  1022
13     Nicolas Maduro                   911
14         Biil-Gates                   829
15           RVALLEJO                   823
16     CARLOSGONZALEZ                   710
17       VICTORARARAT                   704
18           BMAYORGA                   670
19       YESYDVINASCO                   594
20       Lionel_messi                   589
21            LUISGIL                   555
22        JOELVILLADA                   549
23  Faustino Asprilla                   427
24   JULIANVILLANUEVA                   392
25    James Rodriguez                   179
26    Andrea Guerrero                   169
27            HVARGAS                   163
28       ESTEBANMUÑOZ                   135
29           JSANCHEZ                   127
30     JONATANMANZANO                   117
31   Bladimir Padrino                   115
32           YBOLANOS                   109
33      DANIELMAZUERA                    92
34        ALEXISLASSO                    84
35           ADELGADO                    84
36     Vladimir Putin                    76
37      JORGEMOSQUERA                    71
38      HENRYCARABALI                    61
39              admin                    48
40   GEOVANNY Hidalgo                    30
41     DIEGO Maradona                    13
42      WILSONMORALES                     1
43         mensajero1                     1
44         mensajero2                     1

In [ ]:
p6_por_año = pd.read_sql_query("""
SELECT
    f.año,
    c.nombre_cliente,
    s.nombre AS sede,
    COUNT(*) AS total_servicios
FROM fact_servicio h
JOIN dim_cliente c ON h.fk_cliente = c.cliente_key
JOIN dim_sede s ON h.fk_sede = s.sede_key
JOIN dim_fechahora f ON h.fk_fecha_iniciado = f.fecha_hora_key
WHERE h.fk_cliente <> -1 AND h.fk_sede <> -1 AND h.fk_fecha_iniciado <> -1
GROUP BY f.año, c.nombre_cliente, s.nombre
ORDER BY f.año, c.nombre_cliente, total_servicios DESC;
""", etl_conn)
p6_por_año

,año,nombre_cliente,sede,total_servicios
0,2023.0,CARROS DEL PACIFICO (CHINA),PRINCIPAL NORTE / CHINA PACIFICO,3
1,2023.0,CARROS DEL PACIFICO (CHINA),FORDES PASOANCHOS,1
2,2023.0,CARROS DEL PACIFICO (CHINA),FORD CAÑAS FLASCAS,1
3,2023.0,CLINICA CALI -JOVEN,sede aux - cliente 1,51
4,2023.0,CLINICA CALI -JOVEN,VASQUEZ COBO,7
5,2023.0,CLINICA CALI -JOVEN,PRINCIPAL / OCCIDENTE,4
6,2023.0,CLINICA CALI -JOVEN,CAPITOLIO,1
7,2023.0,CLINICA CALI -JOVEN,INGENIO,1
8,2023.0,CLINICA CALI -JOVEN,VILLACOLOMBIA,1
9,2023.0,CLINICA DEPORTIVA DEL SUR,PRINCIPAL /14,3
10,2023.0,CRUZ AZUL-LIFE,REMEDIOZ/ 123,1
11,2023.0,CRUZ AZUL-LIFE,FARALLONES /123,1
12,2024.0,BANCO REGIONAL DE SANGRE BLOD-LIFE,HEMOLIFE,205
13,2024.0,CALI SULUD Y VIDA,VALLE NORTE,508
14,2024.0,CALI SULUD Y VIDA,CAMBULOS,500
15,2024.0,CARROS DEL PACIFICO (CHINA),PRINCIPAL NORTE / CHINA PACIFICO,6849
16,2024.0,CARROS DEL PACIFICO (CHINA),BUSES Y CAMIONES -,5459
17,2024.0,CARROS DEL PACIFICO (CHINA),PALMIRA BODEGA 20 /,1755
18,2024.0,CARROS DEL PACIFICO (CHINA),MEGATALLER / CHINA PACIFICO,1210
19,2024.0,CARROS DEL PACIFICO (CHINA),FORCAS,559
20,2024.0,CARROS DEL PACIFICO (CHINA),FORDES PASOANCHOS,410
21,2024.0,CARROS DEL PACIFICO (CHINA),AUTOPISTA,408
22,2024.0,CARROS DEL PACIFICO (CHINA),FORD CAÑAS FLASCAS,293
23,2024.0,CARROS DEL PACIFICO (CHINA),TULUA BODEGA 26 /,190
24,2024.0,CARROS DEL PACIFICO (CHINA),POPAYAN BODEGA 28 / A,88
25,2024.0,CARROS DEL PACIFICO (CHINA),JMC /,73
26,2024.0,CARROS DEL PACIFICO (CHINA),PASTO BODEGA 29/,37
27,2024.0,CARROS DEL PACIFICO (CHINA),BUGA BODEGA 24,33
28,2024.0,CARROS DEL PACIFICO (CHINA),HYUNDAI /,11
29,2024.0,CARROS DEL PACIFICO (CHINA),PASTO VITRINA /,3
30,2024.0,Cliente 1,sede aux - cliente 1,31
31,2024.0,CLINICA CALI -JOVEN,PRINCIPAL / OCCIDENTE,1007
32,2024.0,CLINICA CALI -JOVEN,VILLACOLOMBIA,875
33,2024.0,CLINICA CALI -JOVEN,CAPITOLIO,754
34,2024.0,CLINICA CALI -JOVEN,VASQUEZ COBO,679
35,2024.0,CLINICA CALI -JOVEN,TORRES DE MARACAIBO,666
36,2024.0,CLINICA CALI -JOVEN,INGENIO,583
37,2024.0,CLINICA CALI -JOVEN,sede aux - cliente 1,22
38,2024.0,CLINICA COFFE -HEALTH,CLINICA CALI,1373
39,2024.0,CLINICA COFFE -HEALTH,CRISTO REY,917
40,2024.0,CLINICA DEL SUR DE CALI,CLINICA FABILUX,1061
41,2024.0,CLINICA DEL SUR DE CALI,BATALLON DISPENSARIO,348
42,2024.0,CLINICA DEPORTIVA DEL SUR,PRINCIPAL /14,289
43,2024.0,CLINICA NEFROLOGOS DE CALI,HEMAS,270
44,2024.0,CLINICA NEFROLOGOS DE CALI,NUEVA HEMATO,26
45,2024.0,CLINICA SAN RAFAEL DE OCCIDENTE,SAN BER NANDO,28
46,2024.0,CRUZ AZUL-LIFE,REMEDIOZ/ 123,82
47,2024.0,CRUZ AZUL-LIFE,FARALLONES /123,29
48,2024.0,CRUZ AZUL-LIFE,DESPACHOS / LOS ROJOS,4
49,2024.0,FUNDACION CLINICA INFANTIL LOS GRITONES,CLUB NOEL,62
50,2024.0,MEDICOS Y SALUD,CIMEX,1
51,2024.0,UNIDAD DE TRAUMA DEL OESTE,TRAUMA ORIENTE,656

In [35]:
p7_por_año = pd.read_sql_query("""
    SELECT
        f.año,
        ROUND(AVG(h.duracion_total_min)::numeric, 2) AS promedio_minutos,
        ROUND((AVG(h.duracion_total_min) / 60)::numeric, 2) AS promedio_horas
    FROM fact_servicio h
    JOIN dim_fechahora f ON h.fk_fecha_iniciado = f.fecha_hora_key
    WHERE h.fk_fecha_cerrado <> -1                           
    GROUP BY f.año
    ORDER BY f.año;
""", etl_conn)
p7_por_año

      año  promedio_minutos  promedio_horas
0  2023.0          82641.53         1377.36
1  2024.0            541.59            9.03

In [38]:
p8_por_año = pd.read_sql_query("""
    SELECT
        f.año,
        ROUND(AVG(h.duracion_iniciado_asignado_min)::numeric, 2) AS asignacion,
        ROUND(AVG(h.duracion_asignado_recogido_min)::numeric, 2) AS recogida,
        ROUND(AVG(h.duracion_recogido_entregado_min)::numeric, 2) AS entrega,
        ROUND(AVG(h.duracion_entregado_cerrado_min)::numeric, 2) AS cierre
    FROM fact_servicio h
    JOIN dim_fechahora f ON h.fk_fecha_iniciado = f.fecha_hora_key
    WHERE h.fk_fecha_cerrado <> -1
    GROUP BY f.año
    ORDER BY f.año;
""", etl_conn)
p8_por_año

      año  asignacion  recogida  entrega   cierre
0  2023.0    36656.41  36363.34  7426.57  2195.20
1  2024.0      108.64     64.91    78.09   289.98

In [39]:
p9_por_año = pd.read_sql_query("""
    SELECT
        f.año,
        dn.nombre_novedad,
        COUNT(*) AS total_ocurrencias
    FROM fact_novedad h
    JOIN dim_novedad dn ON h.fk_tipo_novedad = dn.novedad_key
    JOIN dim_fechahora f ON h.fk_fecha = f.fecha_hora_key
    WHERE h.fk_tipo_novedad <> -1 AND h.fk_fecha <> -1
    GROUP BY f.año, dn.nombre_novedad
    ORDER BY f.año, total_ocurrencias DESC;
""", etl_conn)
p9_por_año

      año          nombre_novedad  total_ocurrencias
0  2023.0  Novedades del servicio                  9
1  2023.0      No puedo continuar                  8
2  2024.0  Novedades del servicio               3883
3  2024.0      No puedo continuar               1308

In [21]:
print("Usuario:", config_etl['user'])

Usuario: daniel